namespace TaskWorker.Model
{
    public class Production
    {
        public string INSURANCE_BRANCH { get; set; }
        public string INS_POLICY_KEY { get; set; }
        public string INS_POLICY_REF { get; set; }
        public string FOB { get; set; }
        public string BROKER_CODE { get; set; }
        public string CURRENCY { get; set; }
        public string RENEWAL_POLICY { get; set; }
        public string INS_PREVPOLICY_KEY { get; set; }
        public string NETWORK_KEY { get; set; }
        public string POLICY_INDGRP { get; set; }
        public string HOLDER_GENDER { get; set; }
        public string HOLDER_FIRST_NAME_EN { get; set; }
        public string HOLDER_MIDDLE_NAME_EN { get; set; }
        public string HOLDER_LAST_NAME_EN { get; set; }
        public string HOLDER_FIRST_NAME_AR { get; set; }
        public string HOLDER_MIDDLE_NAME_AR { get; set; }
        public string HOLDER_LAST_NAME_AR { get; set; }
        public string HOLDER_DATE_OF_BIRTH { get; set; }
        public string HOLDER_PHONE_NUMBER { get; set; }
        public string POLICY_END { get; set; }
        public string END_CODE { get; set; }
        public string EFFECTIVE { get; set; }
        public string EXPIRY { get; set; }
        public string NOTES { get; set; }
        public string SCHEDULE_NO { get; set; }
        public string PRODUCT { get; set; }
        public string INSURED_GENDER { get; set; }
        public string INSURED_FIRST_NAME_EN { get; set; }
        public string INSURED_MIDDLE_NAME_EN { get; set; }
        public string INSURED_LAST_NAME_EN { get; set; }
        public string INSURED_FIRST_NAME_AR { get; set; }
        public string INSURED_MIDDLE_NAME_AR { get; set; }
        public string INSURED_LAST_NAME_AR { get; set; }
        public string INSURED_DATE_OF_BIRTH { get; set; }
        public string INSURED_PHONE_NUMBER { get; set; }
        public string RENEWAL_SCHEDULE { get; set; }
        public string SUM_INSURED { get; set; }
        public string PLATECODE { get; set; }
        public string PLATE { get; set; }
        public string CHASSIS { get; set; }
        public string MAKE { get; set; }
        public string MODEL { get; set; }
        public string USAGE { get; set; }
        public string HP { get; set; }
        public string YEAR { get; set; }
        public string BODY { get; set; }
        public string WEIGHT { get; set; }
        public string SEAT { get; set; }
        public string ENGINE { get; set; }
        public string COLOR { get; set; }
        public string CC { get; set; }
        public string TRANS { get; set; }
        public string DOORS { get; set; }
        public string DRLIC { get; set; }
        public string DRLICINC { get; set; }
        public string DRLICEXP { get; set; }
        public string DEPRECIATION_SCHEDULE { get; set; }
        public string COVER { get; set; }
        public string SUMINSURED { get; set; }
        public string DEDUCTIBLE_CODE { get; set; }
        public string DEDUCTIBLE_TYPE { get; set; }
        public string DEDUCTIBLE_AMNT { get; set; }
        public string DEPRECIATION_SCHEDULECOVER { get; set; }
        public string ALLOWED_QTTY { get; set; }
        public string ALLOWED_DISTANCE_UNIT { get; set; }
        public string ALLOWED_DISTANCE { get; set; }
        public string CLAUSE { get; set; }
    }
}
